#📌 Урок: Работа с файлами
##📖 Теоретический минимум

Текстовые файлы (.txt) - простые файлы с неструктурированным текстом

CSV (Comma-Separated Values) - табличные данные с разделителями

Excel (.xlsx, .xls) - электронные таблицы с расширенными возможностями

JSON - структурированные данные в формате ключ-значение

Бинарные файлы - изображения, PDF и другие нетекстовые форматы

# 🔹 Основные операции с файлами
Открытие/закрытие файла

Чтение данных

Запись данных

Обработка больших файлов


#📖 Материалы

https://vkvideo.ru/video-194554202_456239677

https://vkvideo.ru/video-194554202_456239682









# 🏆 Задания

## 1️⃣ Работа с текстовыми файлами
**Задача:**
 Создать текстовый файл, записать в него str данные и прочитать обратно

In [34]:
with open('task1.txt', 'w') as file:
    file.write('Создал текстовый файл, записал в него str данные и прочитал обратно')

with open('task1.txt', 'r') as file:
    print(file.read())

Создал текстовый файл, записал в него str данные и прочитал обратно



## 2️⃣ Работа с CSV файлами

**Задача:**

Создать CSV файл с табличными данными, записать и прочитать его



In [5]:
import pandas as pd

data = {
    'date': ['2021-07-01', '2024-08-01', '2022-09-01'],
    'field_id': ['Новое', 'Старое', 'Старое'],
    'oil': [128, 3, 1],
    'gas': [0, 15, 25],
    'year': [2021, 2024, 2022]
}

df = pd.DataFrame(data)

df.to_csv('production_data.csv', index=False, encoding='utf-8')
df_read = pd.read_csv('production_data.csv', parse_dates=['date'])

print(df_read)

        date field_id  oil  gas  year
0 2021-07-01    Новое  128    0  2021
1 2024-08-01   Старое    3   15  2024
2 2022-09-01   Старое    1   25  2022


## 3️⃣  Работа с Excel файлами
**Задача:** Создать Excel файл и прочитать данные из него

Используйте библиотеку pandas

---



In [7]:
import pandas as pd

data = {
    'date': ['2021-07-01', '2024-08-01', '2022-09-01'],
    'field_id': ['Новое', 'Старое', 'Старое'],
    'oil': [128, 3, 1],
    'gas': [0, 15, 25],
    'year': [2021, 2024, 2022]
}
df = pd.DataFrame(data)

df.to_excel('production.xlsx', index=False, sheet_name='data')
df_read = pd.read_excel('production.xlsx', sheet_name='data')

print(df_read)

         date field_id  oil  gas  year
0  2021-07-01    Новое  128    0  2021
1  2024-08-01   Старое    3   15  2024
2  2022-09-01   Старое    1   25  2022



## 4️⃣  Чтение больших файлов по частям


**Задача:** Обработать файл построчно без загрузки в память целиком

Реализуйте чанки самостоятельно или воспользуйтесь chunk из pandas

---




In [33]:
import pandas as pd

file_path = 'production_data_1.csv'
for i, chunk in enumerate(pd.read_csv(file_path, chunksize=4)):
    print(chunk.head(6))

         date field_id  oil  gas  year
0  2021-07-01    Новое  128    0  2021
1  2024-08-01   Старое    3   15  2024
2  2022-09-01   Старое    1   25  2022
3  2021-07-01    Новое  128    0  2022
         date field_id  oil  gas  year
4  2024-08-01   Старое    3   15  2025
5  2022-09-01   Старое    1   25  2023
6  2021-07-01    Новое  128    0  2023
7  2024-08-01   Старое    3   15  2026
          date field_id  oil  gas  year
8   2022-09-01   Старое    1   25  2024
9   2021-07-01    Новое  128    0  2024
10  2024-08-01   Старое    3   15  2027
11  2022-09-01   Старое    1   25  2025
          date field_id  oil  gas  year
12  2021-07-01    Новое  128    0  2025
13  2024-08-01   Старое    3   15  2028
14  2022-09-01   Старое    1   25  2026
15  2021-07-01    Новое  128    0  2026
          date field_id  oil  gas  year
16  2024-08-01   Старое    3   15  2029
17  2022-09-01   Старое    1   25  2027
18  2021-07-01    Новое  128    0  2027
19  2024-08-01   Старое    3   15  2030
          


## 5️⃣ Чтение JPEG файла
**Задача:**

Создайте изображение 21х21 пиксель в формате JPEG

Прочитайте JPEG файл в бинарном режиме

Выведете прочитанный файл как массив интенсивности пикселей

---


In [36]:
from PIL import Image
import numpy as np

d = np.random.randint(0, 256, (6, 4, 3), dtype=np.uint8)
image = Image.fromarray(d)
image.save('image_5.jpg')

with open('image_5.jpg', 'rb') as file:
    bytes = file.read()

color_arr = np.array(Image.open('image_5.jpg'))
print(color_arr)


[[[166  56 153]
  [122  12 109]
  [127 169 185]
  [  0  34  50]]

 [[121  11 108]
  [195  85 182]
  [ 81 123 139]
  [129 171 187]]

 [[108  70 129]
  [ 99  61 120]
  [123 163 165]
  [ 92 132 134]]

 [[128  90 149]
  [141 103 162]
  [139 179 181]
  [ 59  99 101]]

 [[ 81 130 144]
  [ 41  90 104]
  [155 185 175]
  [ 81 111 101]]

 [[ 31  80  94]
  [140 189 203]
  [  0  25  15]
  [ 80 110 100]]]
